var annotated_dup =
[
    [ "AddNebulaDialog", "classAddNebulaDialog.html", "classAddNebulaDialog" ],
    [ "AddStarSystemDialog", "classAddStarSystemDialog.html", "classAddStarSystemDialog" ],
    [ "Algorithms", "classAlgorithms.html", "classAlgorithms" ],
    [ "BFSAlgorithm", "classBFSAlgorithm.html", "classBFSAlgorithm" ],
    [ "BFSMatrixAlgorithm", "classBFSMatrixAlgorithm.html", "classBFSMatrixAlgorithm" ],
    [ "CelestialObject", "classCelestialObject.html", "classCelestialObject" ],
    [ "DFSAlgorithm", "classDFSAlgorithm.html", "classDFSAlgorithm" ],
    [ "DFSMatrixAlgorithm", "classDFSMatrixAlgorithm.html", "classDFSMatrixAlgorithm" ],
    [ "DijkstraListAlgorithm", "classDijkstraListAlgorithm.html", "classDijkstraListAlgorithm" ],
    [ "DijkstraMatrixAlgorithm", "classDijkstraMatrixAlgorithm.html", "classDijkstraMatrixAlgorithm" ],
    [ "Edge", "classEdge.html", "classEdge" ],
    [ "EditNebulaDialog", "classEditNebulaDialog.html", "classEditNebulaDialog" ],
    [ "EditStarSystemDialog", "classEditStarSystemDialog.html", "classEditStarSystemDialog" ],
    [ "Galaxy", "classGalaxy.html", "classGalaxy" ],
    [ "GalaxyEditDialog", "classGalaxyEditDialog.html", "classGalaxyEditDialog" ],
    [ "GalaxyView", "classGalaxyView.html", "classGalaxyView" ],
    [ "Graph", "classGraph.html", "classGraph" ],
    [ "GraphAlgorithm", "classGraphAlgorithm.html", "classGraphAlgorithm" ],
    [ "GraphList", "classGraphList.html", "classGraphList" ],
    [ "GraphMatrix", "classGraphMatrix.html", "classGraphMatrix" ],
    [ "GraphWidget", "classGraphWidget.html", "classGraphWidget" ],
    [ "IsConnectedList", "classIsConnectedList.html", "classIsConnectedList" ],
    [ "IsConnectedMatrix", "classIsConnectedMatrix.html", "classIsConnectedMatrix" ],
    [ "Nebula", "classNebula.html", "classNebula" ],
    [ "Planet", "classPlanet.html", "classPlanet" ],
    [ "Queue", "classQueue.html", "classQueue" ],
    [ "RandomGenerator", "classRandomGenerator.html", "classRandomGenerator" ],
    [ "Star", "classStar.html", "classStar" ],
    [ "StarSystem", "classStarSystem.html", "classStarSystem" ],
    [ "Vertex", "classVertex.html", "classVertex" ],
    [ "W_Edge", "structW__Edge.html", "structW__Edge" ],
    [ "W_Vertex", "structW__Vertex.html", "structW__Vertex" ],
    [ "WindowInterface", "classWindowInterface.html", "classWindowInterface" ]
];